//
//  Mitzvah.swift
//  Taryag Mitzvot
//
//  Created by Snir Avrahami on 3/3/23.
//

import Foundation

struct Mitzvah: Hashable {
    let title: String
    let engText: String
    let hebText: String
    let verse: String
    var tags: [String]
    
    init(title: String, engText: String, hebText: String, verse: String, tags: [String]) {
        self.title = title
        self.engText = engText
        self.hebText = hebText
        self.verse = verse
        self.tags = tags
    }
    
    static func addMitzvot() -> [Mitzvah] {
        return [
            Mitzvah(title: "Know there is a God", engText: "I am the Lord, your God, Who took you out of the land of Egypt, out of the house of bondage.", hebText: "אָֽנֹכִ֨י יְהֹוָ֣ה אֱלֹהֶ֔יךָ אֲשֶׁ֣ר הֽוֹצֵאתִ֩יךָ֩ מֵאֶ֨רֶץ מִצְרַ֜יִם מִבֵּ֣ית עֲבָדִ֗ים:", verse: "Shemot 20:2", tags: ["Ten Commandments", "Positive", "Applicable", "Shemot"]),
            Mitzvah(title: "Do not have other gods before the Lord", engText: "You shall not have the gods of others in My presence.", hebText: "לֹ֣א יִֽהְיֶ֣ה־לְךָ֩ אֱלֹהִ֨ים אֲחֵרִ֜ים עַל־פָּנַ֗י:", verse: "Shemot 20:3", tags: ["Ten Commandments", "Idolatry", "Avodah Zarah", "Negative", "Applicable", "Shemot"]),
            Mitzvah(title: "Know the Lord is one", engText: "Hear, O Israel: The Lord is our God; the Lord is one.", hebText: "שְׁמַ֖ע יִשְׂרָאֵ֑ל יְהֹוָ֥ה אֱלֹהֵ֖ינוּ יְהֹוָ֥ה | אֶחָֽד:", verse: "Devarim 6:4", tags: ["Positive", "Idolatry", "Avodah Zarah", "Applicable", "Devarim"]),
            Mitzvah(title: "Love the Lord", engText: "And you shall love the Lord, your God, with all your heart and with all your soul, and with all your means.", hebText: "וְאָ֣הַבְתָּ֔ אֵ֖ת יְהֹוָ֣ה אֱלֹהֶ֑יךָ בְּכָל־לְבָֽבְךָ֥ וּבְכָל־נַפְשְׁךָ֖ וּבְכָל־מְאֹדֶֽךָ:", verse: "Devarim 6:5", tags: ["Relation to God", "Positive", "Applicable", "Devarim"]),
            Mitzvah(title: "Fear the Lord", engText: "You shall fear the Lord, your God, worship Him, and cleave to Him and swear by His Name.", hebText: "אֶת־יְהֹוָ֧ה אֱלֹהֶ֛יךָ תִּירָ֖א אֹת֣וֹ תַֽעֲבֹ֑ד וּב֣וֹ תִדְבָּ֔ק וּבִשְׁמ֖וֹ תִּשָּׁבֵֽעַ:", verse: "Devarim 10:20", tags: ["Relation to God", "Positive", "Applicable", "Devarim"]),
            Mitzvah(title: "Sanctify the name of the Lord", engText: "You shall not desecrate My Holy Name. I shall be sanctified amidst the children of Israel. I am the Lord Who sanctifies you", hebText: "וְלֹ֤א תְחַלְּלוּ֙ אֶת־שֵׁ֣ם קָדְשִׁ֔י וְנִ֨קְדַּשְׁתִּ֔י בְּת֖וֹךְ בְּנֵ֣י יִשְׂרָאֵ֑ל אֲנִ֥י יְהֹוָ֖ה מְקַדִּשְׁכֶֽם", verse: "Vayikra 22:32", tags: ["Speech", "Positive", "Applicable", "Vayikra"]),
            Mitzvah(title: "Don't profane the name of the Lord", engText: "You shall not desecrate My Holy Name. I shall be sanctified amidst the children of Israel. I am the Lord Who sanctifies you", hebText: "וְלֹ֤א תְחַלְּלוּ֙ אֶת־שֵׁ֣ם קָדְשִׁ֔י וְנִ֨קְדַּשְׁתִּ֔י בְּת֖וֹךְ בְּנֵ֣י יִשְׂרָאֵ֑ל אֲנִ֥י יְהֹוָ֖ה מְקַדִּשְׁכֶֽם", verse: "Vayikra 22:32", tags: ["Speech", "Blasphemy", "Negative", "Applicable", "Vayikra"]),
            Mitzvah(title: "Do not destroy objects associated with the name of the Lord", engText: "And you shall tear down their altars, smash their monuments, burn their asherim with fire, cut down the graven images of their gods, and destroy their name from that place. 4You shall not do so to the Lord, your God.", hebText: "וְנִתַּצְתֶּ֣ם אֶת־מִזְבְּחֹתָ֗ם וְשִׁבַּרְתֶּם֙ אֶת־מַצֵּ֣בֹתָ֔ם וַֽאֲשֵֽׁרֵיהֶם֙ תִּשְׂרְפ֣וּן בָּאֵ֔שׁ וּפְסִילֵ֥י אֱלֹֽהֵיהֶ֖ם תְּגַדֵּע֑וּן וְאִבַּדְתֶּ֣ם אֶת־שְׁמָ֔ם מִן־הַמָּק֖וֹם הַהֽוּא: ד לֹא־תַֽעֲשׂ֣וּן כֵּ֔ן לַֽיהֹוָ֖ה אֱלֹֽהֵיכֶֽם", verse: "Devarim 12:3-4", tags: ["Negative", "Applicable", "Devarim"]),
            Mitzvah(title: "Listen to the prophet speaking in God's name", engText: "A prophet from among you, from your brothers, like me, the Lord, your God will set up for you; you shall hearken to him. 16 According to all that you asked of the Lord, your God, in Horeb, on the day of the assembly, saying, \"Let me not continue to hear the voice of the Lord, my God, and let me no longer see this great fire, so that I will not die.\" 17 And the Lord said to me, \"They have done well in what they have spoken.\" 18 I will set up a prophet for them from among their brothers like you, and I will put My words into his mouth, and he will speak to them all that I command him.", hebText: "נָבִ֨יא מִקִּרְבְּךָ֤ מֵֽאַחֶ֨יךָ֙ כָּמֹ֔נִי יָקִ֥ים לְךָ֖ יְהֹוָ֣ה אֱלֹהֶ֑יךָ אֵלָ֖יו תִּשְׁמָעֽוּן: כְּכֹ֨ל אֲשֶׁר־שָׁאַ֜לְתָּ מֵעִ֨ם יְהֹוָ֤ה אֱלֹהֶ֨יךָ֙ בְּחֹרֵ֔ב בְּי֥וֹם הַקָּהָ֖ל לֵאמֹ֑ר לֹ֣א אֹסֵ֗ף לִשְׁמֹ֨עַ֙ אֶת־קוֹל֙ יְהֹוָ֣ה אֱלֹהָ֔י וְאֶת־הָאֵ֨שׁ הַגְּדֹלָ֥ה הַזֹּ֛את לֹֽא־אֶרְאֶ֥ה ע֖וֹד וְלֹ֥א אָמֽוּת: וַיֹּ֥אמֶר יְהֹוָ֖ה אֵלָ֑י הֵיטִ֖יבוּ אֲשֶׁ֥ר דִּבֵּֽרוּ: נָבִ֨יא אָקִ֥ים לָהֶ֛ם מִקֶּ֥רֶב אֲחֵיהֶ֖ם כָּמ֑וֹךָ וְנָֽתַתִּ֤י דְבָרַי֙ בְּפִ֔יו וְדִבֶּ֣ר אֲלֵיהֶ֔ם אֵ֖ת כָּל־אֲשֶׁ֥ר אֲצַוֶּֽנּוּ: וְהָיָ֗ה הָאִישׁ֙ אֲשֶׁ֤ר לֹֽא־יִשְׁמַע֙ אֶל־דְּבָרַ֔י אֲשֶׁ֥ר יְדַבֵּ֖ר בִּשְׁמִ֑י אָֽנֹכִ֖י אֶדְר֥שׁ מֵֽעִמּֽוֹ:", verse: "Devarim 18:15-18", tags: ["Not Applicable", "Devarim"]),
            Mitzvah(title: "Do not unduly test the prophet", engText: "You shall not try the Lord, your God, as you tried Him in Massah.", hebText: "לֹ֣א תְנַסּ֔וּ אֶת־יְהֹוָ֖ה אֱלֹֽהֵיכֶ֑ם כַּֽאֲשֶׁ֥ר נִסִּיתֶ֖ם בַּמַּסָּֽה:", verse: "Devarim 6:16", tags: ["Negative", "Applicable", "Devarim"]),
            Mitzvah(title: "Emulate the ways of the Lord", engText: "The Lord will establish you as His holy people as He swore to you, if you observe the commandments of the Lord, your God, and walk in His ways.", hebText: "יְקִֽימְךָ֙ יְהֹוָ֥ה לוֹ֙ לְעַ֣ם קָד֔וֹשׁ כַּֽאֲשֶׁ֖ר נִשְׁבַּע־לָ֑ךְ כִּ֣י תִשְׁמֹ֗ר אֶת־מִצְו‍ֹת֙ יְהֹוָ֣ה אֱלֹהֶ֔יךָ וְהָֽלַכְתָּ֖ בִּדְרָכָֽיו:", verse: "Devarim 28:9", tags: ["Positive", "Applicable", "Devarim"]),
            Mitzvah(title: "Cleave to God", engText: "You shall fear the Lord, your God, worship Him, and cleave to Him and swear by His Name.", hebText: "אֶת־יְהֹוָ֧ה אֱלֹהֶ֛יךָ תִּירָ֖א אֹת֣וֹ תַֽעֲבֹ֑ד וּב֣וֹ תִדְבָּ֔ק וּבִשְׁמ֖וֹ תִּשָּׁבֵֽעַ:", verse: "Devarim 10:20", tags: ["Positive", "Applicable", "Devarim"]),
            Mitzvah(title: "Love your fellow Jews", engText: "You shall neither take revenge from nor bear a grudge against the members of your people; you shall love your neighbor as yourself. I am the Lord.", hebText: "לֹֽא־תִקֹּ֤ם וְלֹֽא־תִטֹּר֙ אֶת־בְּנֵ֣י עַמֶּ֔ךָ וְאָֽהַבְתָּ֥ לְרֵֽעֲךָ֖ כָּמ֑וֹךָ אֲנִ֖י יְהוָֹֽה:", verse: "Vayikra 19:18", tags: ["Positive", "Applicable", "Vayikra"]),
            Mitzvah(title: "Love the converts", engText: "You shall love the stranger, for you were strangers in the land of Egypt.", hebText: "וַֽאֲהַבְתֶּ֖ם אֶת־הַגֵּ֑ר כִּֽי־גֵרִ֥ים הֱיִיתֶ֖ם בְּאֶ֥רֶץ מִצְרָֽיִם:", verse: "Devarim 10:19", tags: ["Positive", "Applicable", "Devarim"]),
            Mitzvah(title: "Do not hate your fellow Jew", engText: "You shall not hate your brother in your heart. You shall surely rebuke your fellow, but you shall not bear a sin on his account.", hebText: "לֹֽא־תִשְׂנָ֥א אֶת־אָחִ֖יךָ בִּלְבָבֶ֑ךָ הוֹכֵ֤חַ תּוֹכִ֨יחַ֙ אֶת־עֲמִיתֶ֔ךָ וְלֹֽא־תִשָּׂ֥א עָלָ֖יו חֵֽטְא:", verse: "Vayikra 19:17", tags: ["Negative", "Applicable", "Vayikra"]),
            Mitzvah(title: "Rebuke wrongdoers", engText: "You shall not hate your brother in your heart. You shall surely rebuke your fellow, but you shall not bear a sin on his account.", hebText: "לֹֽא־תִשְׂנָ֥א אֶת־אָחִ֖יךָ בִּלְבָבֶ֑ךָ הוֹכֵ֤חַ תּוֹכִ֨יחַ֙ אֶת־עֲמִיתֶ֔ךָ וְלֹֽא־תִשָּׂ֥א עָלָ֖יו חֵֽטְא:", verse: "Vayikra 19:17", tags: ["Positive", "Applicable", "Speech", "Vayikra"]),
            Mitzvah(title: "Do not embarrass others", engText: "You shall not hate your brother in your heart. You shall surely rebuke your fellow, but you shall not bear a sin on his account.", hebText: "לֹֽא־תִשְׂנָ֥א אֶת־אָחִ֖יךָ בִּלְבָבֶ֑ךָ הוֹכֵ֤חַ תּוֹכִ֨יחַ֙ אֶת־עֲמִיתֶ֔ךָ וְלֹֽא־תִשָּׂ֥א עָלָ֖יו חֵֽטְא:", verse: "Vayikra 19:17", tags: ["Applicable", "Negative", "Speech", "Lashon HaRa", "Vayikra"]),
            Mitzvah(title: "Do not oppress the weak", engText: "You shall not oppress any widow or orphan.", hebText: "כָּל־אַלְמָנָ֥ה וְיָת֖וֹם לֹ֥א תְעַנּֽוּן:", verse: "Shemot 22:21", tags: ["Negative", "Applicable", "Children", "Shemot"]),
            Mitzvah(title: "Do not gossip", engText: "You shall not go around as a gossipmonger amidst your people. You shall not stand by [the shedding of] your fellow's blood. I am the Lord.", hebText: "לֹֽא־תֵלֵ֤ךְ רָכִיל֙ בְּעַמֶּ֔יךָ לֹ֥א תַֽעֲמֹ֖ד עַל־דַּ֣ם רֵעֶ֑ךָ אֲנִ֖י יְהוָֹֽה:", verse: "Vayikra 19:16", tags: ["Applicable", "Negative", "Speech", "Lashon HaRa", "Vayikra"]),
            Mitzvah(title: "Do not take revenge", engText: "You shall neither take revenge from nor bear a grudge against the members of your people; you shall love your neighbor as yourself. I am the Lord.", hebText: "לֹֽא־תִקֹּ֤ם וְלֹֽא־תִטֹּר֙ אֶת־בְּנֵ֣י עַמֶּ֔ךָ וְאָֽהַבְתָּ֥ לְרֵֽעֲךָ֖ כָּמ֑וֹךָ אֲנִ֖י יְהוָֹֽה:", verse: "Vayikra 19:18", tags: ["Negative", "Applicable", "Vayikra"]),
            Mitzvah(title: "Do not keep grudges", engText: "You shall neither take revenge from nor bear a grudge against the members of your people; you shall love your neighbor as yourself. I am the Lord.", hebText: "לֹֽא־תִקֹּ֤ם וְלֹֽא־תִטֹּר֙ אֶת־בְּנֵ֣י עַמֶּ֔ךָ וְאָֽהַבְתָּ֥ לְרֵֽעֲךָ֖ כָּמ֑וֹךָ אֲנִ֖י יְהוָֹֽה:", verse: "Vayikra 19:18", tags: ["Negative", "Applicable", "Vayikra"]),
            Mitzvah(title: "Learn and teach Torah", engText: "And you shall teach them to your sons and speak of them when you sit in your house, and when you walk on the way, and when you lie down and when you rise up.", hebText: "וְשִׁנַּנְתָּ֣ם לְבָנֶ֔יךָ וְדִבַּרְתָּ֖ בָּ֑ם בְּשִׁבְתְּךָ֤ בְּבֵיתֶ֨ךָ֙ וּבְלֶכְתְּךָ֣ בַדֶּ֔רֶךְ וּבְשָׁכְבְּךָ֖ וּבְקוּמֶֽךָ:", verse: "Devarim 6:7", tags: ["Positive", "Applicable", "Speech", "Children", "Devarim"]),
            Mitzvah(title: "Venerate the elderly and those who know and teach Torah", engText: "You shall rise before a venerable person and you shall respect the elderly, and you shall fear your God. I am the Lord.", hebText: "מִפְּנֵ֤י שֵׂיבָה֙ תָּק֔וּם וְהָֽדַרְתָּ֖ פְּנֵ֣י זָקֵ֑ן וְיָרֵ֥אתָ מֵּֽאֱלֹהֶ֖יךָ אֲנִ֥י יְהוָֹֽה:", verse: "Vayikra 19:32", tags: ["Positive", "Applicable", "Vauikra"]),
            Mitzvah(title: "Do not turn to idols", engText: "You shall not turn to the worthless idols, nor shall you make molten deities for yourselves. I am the Lord, your God.", hebText: "אַל־תִּפְנוּ֙ אֶל־הָ֣אֱלִילִ֔ם וֵֽאלֹהֵי֙ מַסֵּכָ֔ה לֹ֥א תַֽעֲשׂ֖וּ לָכֶ֑ם אֲנִ֖י יְהוָֹ֥ה אֱלֹֽהֵיכֶֽם:", verse: "Vayikra 19:4", tags: ["Applicable", "Negative", "Idolatry", "Avodah Zarah", "Vayikra"]),
            Mitzvah(title: "Do not follow the whims of your heart or what your eyes see", engText: "This shall be fringes for you, and when you see it, you will remember all the commandments of the Lord to perform them, and you shall not wander after your hearts and after your eyes after which you are going astray.", hebText: "וְהָיָ֣ה לָכֶם֘ לְצִיצִת֒ וּרְאִיתֶ֣ם אֹת֗וֹ וּזְכַרְתֶּם֙ אֶת־כָּל־מִצְוֹ֣ת יְהֹוָ֔ה וַֽעֲשִׂיתֶ֖ם אֹתָ֑ם וְלֹֽא־תָת֜וּרוּ אַֽחֲרֵ֤י לְבַבְכֶם֙ וְאַֽחֲרֵ֣י עֵֽינֵיכֶ֔ם אֲשֶׁר־אַתֶּ֥ם זֹנִ֖ים אַֽחֲרֵיהֶֽם:", verse: "BaMidbar 15:39", tags: ["Negative", "Applicable", "BaMidbar"]),
            Mitzvah(title: "Do not blaspheme", engText: "You shall not curse a judge, neither shall you curse a prince among your people.", hebText: "אֱלֹהִ֖ים לֹ֣א תְקַלֵּ֑ל וְנָשִׂ֥יא בְעַמְּךָ֖ לֹ֥א תָאֹֽר:", verse: "Shemot 22:27", tags: ["Negative", "Applicable", "Speech", "Blasphemy", "Lashon HaRa", "Shemot"]),
            Mitzvah(title: "Do not worship idols in the manner they are worshiped", engText: "You shall neither prostrate yourself before them nor worship them, for I, the Lord, your God, am a zealous God, Who visits the iniquity of the fathers upon the sons, upon the third and the fourth generation of those who hate Me", hebText: "לֹֽא־תִשְׁתַּֽחֲוֶ֣ה לָהֶם֘ וְלֹ֣א תָֽעָבְדֵם֒ כִּ֣י אָֽנֹכִ֞י יְהֹוָ֤ה אֱלֹהֶ֨יךָ֙ אֵ֣ל קַנָּ֔א פֹּ֠קֵ֠ד עֲוֹ֨ן אָבֹ֧ת עַל־בָּנִ֛ים עַל־שִׁלֵּשִׁ֥ים וְעַל־רִבֵּעִ֖ים לְשֽׂנְאָ֑י:", verse: "Shemot 20:5", tags: ["Negative", "Applicable", "Ten Commandments", "Idolatry", "Avodah Zarah", "Shemot"]),
            Mitzvah(title: "Do not bow down to idols", engText: "You shall neither prostrate yourself before them nor worship them, for I, the Lord, your God, am a zealous God, Who visits the iniquity of the fathers upon the sons, upon the third and the fourth generation of those who hate Me", hebText: "לֹֽא־תִשְׁתַּֽחֲוֶ֣ה לָהֶם֘ וְלֹ֣א תָֽעָבְדֵם֒ כִּ֣י אָֽנֹכִ֞י יְהֹוָ֤ה אֱלֹהֶ֨יךָ֙ אֵ֣ל קַנָּ֔א פֹּ֠קֵ֠ד עֲוֹ֨ן אָבֹ֧ת עַל־בָּנִ֛ים עַל־שִׁלֵּשִׁ֥ים וְעַל־רִבֵּעִ֖ים לְשֽׂנְאָ֑י:", verse: "Shemot 20:5", tags: ["Negative", "Applicable", "Ten Commandments", "Idolatry", "Avodah Zarah", "Shemot"]),
            Mitzvah(title: "Do not make for yourself an idol", engText: "You shall not make for yourself a graven image or any likeness which is in the heavens above, which is on the earth below, or which is in the water beneath the earth.", hebText: "לֹ֣א תַֽעֲשֶׂה־לְּךָ֣ פֶ֣סֶל | וְכָל־תְּמוּנָ֡ה אֲשֶׁ֣ר בַּשָּׁמַ֣יִם | מִמַּ֡עַל וַֽאֲשֶׁר֩ בָּאָ֨רֶץ מִתַּ֜חַת וַֽאֲשֶׁ֣ר בַּמַּ֣יִם | מִתַּ֣חַת לָאָ֗רֶץ:", verse: "Shemot 20:4", tags: ["Negative", "Applicable", "Ten Commandments", "Idolatry", "Avodah Zarah", "Shemot"]),
            Mitzvah(title: "Do not make idols for others", engText: "You shall not turn to the worthless idols, nor shall you make molten deities for yourselves. I am the Lord, your God.", hebText: "אַל־תִּפְנוּ֙ אֶל־הָ֣אֱלִילִ֔ם וֵֽאלֹהֵי֙ מַסֵּכָ֔ה לֹ֥א תַֽעֲשׂ֖וּ לָכֶ֑ם אֲנִ֖י יְהוָֹ֥ה אֱלֹֽהֵיכֶֽם:", verse: "Vayikra 19:4", tags: ["Negative", "Applicable", "Idolatry", "Avodah Zarah", "Vayikra"]),
            Mitzvah(title: "Do not make human forms even for decorative purposes", engText: "You shall not make [images of anything that is] with Me. Gods of silver or gods of gold you shall not make for yourselves.", hebText: "לֹ֥א תַֽעֲשׂ֖וּן אִתִּ֑י אֱלֹ֤הֵי כֶ֨סֶף֙ וֵֽאלֹהֵ֣י זָהָ֔ב לֹ֥א תַֽעֲשׂ֖וּ לָכֶֽם:", verse: "Shemot 20:20", tags: ["Negative", "Applicable", "Idolatry", "Avodah Zarah", "Shemot"]),
            Mitzvah(title: "Do not turn a city to idolatry", engText: "Concerning all that I have said to you you shall beware, and the name of the gods of others you shall not mention; it shall not be heard through your mouth.", hebText: "וּבְכֹ֛ל אֲשֶׁר־אָמַ֥רְתִּי אֲלֵיכֶ֖ם תִּשָּׁמֵ֑רוּ וְשֵׁ֨ם אֱלֹהִ֤ים אֲחֵרִים֙ לֹ֣א תַזְכִּ֔ירוּ לֹ֥א יִשָּׁמַ֖ע עַל־פִּֽיךָ:", verse: "Shemot 23:13", tags: ["Negative", "Applicable", "Idolatry", "Avodah Zarah", "Shemot"]),
            Mitzvah(title: "Burn a city which has turned to idolatry", engText: "And you shall collect all its spoil into the midst of its open square, and burn with fire the city and all its spoil, completely, for the Lord, your God; and it shall be a heap of destruction forever, never to be rebuilt.", hebText: "וְאֶת־כָּל־שְׁלָלָ֗הּ תִּקְבֹּץ֘ אֶל־תּ֣וֹךְ רְחֹבָהּ֒ וְשָֽׂרַפְתָּ֣ בָאֵ֗שׁ אֶת־הָעִ֤יר וְאֶת־כָּל־שְׁלָלָהּ֙ כָּלִ֔יל לַֽיהֹוָ֖ה אֱלֹהֶ֑יךָ וְהָֽיְתָה֙ תֵּ֣ל עוֹלָ֔ם לֹ֥א תִבָּנֶ֖ה עֽוֹד:", verse: "Devarim 13:17", tags: ["Positive", "Not Applicable", "Idolatry", "Devarim"]),
            Mitzvah(title: "Do not rebuild as a city the city that has turned to idolatry", engText: "And you shall collect all its spoil into the midst of its open square, and burn with fire the city and all its spoil, completely, for the Lord, your God; and it shall be a heap of destruction forever, never to be rebuilt.", hebText: "וְאֶת־כָּל־שְׁלָלָ֗הּ תִּקְבֹּץ֘ אֶל־תּ֣וֹךְ רְחֹבָהּ֒ וְשָֽׂרַפְתָּ֣ בָאֵ֗שׁ אֶת־הָעִ֤יר וְאֶת־כָּל־שְׁלָלָהּ֙ כָּלִ֔יל לַֽיהֹוָ֖ה אֱלֹהֶ֑יךָ וְהָֽיְתָה֙ תֵּ֣ל עוֹלָ֔ם לֹ֥א תִבָּנֶ֖ה עֽוֹד:", verse: "Devarim 13:17", tags: ["Negative", "Applicable", "Idolatry", "Devarim"]),
            Mitzvah(title: "Do not derive benifit from a city which has turned to idolatry", engText: "And nothing that is doomed to destruction shall cling to your hand, so that the Lord may return from His fierce wrath, and grant you compassion, and be compassionate with you, and multiply you, as He swore to your forefathers.", hebText: "וְלֹֽא־יִדְבַּ֧ק בְּיָֽדְךָ֛ מְא֖וּמָה מִן־הַחֵ֑רֶם לְמַ֩עַן֩ יָשׁ֨וּב יְהֹוָ֜ה מֵֽחֲר֣וֹן אַפּ֗וֹ וְנָֽתַן־לְךָ֤ רַֽחֲמִים֙ וְרִֽחַמְךָ֣ וְהִרְבֶּ֔ךָ כַּֽאֲשֶׁ֥ר נִשְׁבַּ֖ע לַֽאֲבֹתֶֽיךָ:", verse: "Devarim 13:18", tags: ["Negative", "Applicable", "Idolatry", "Devarim"]),
            Mitzvah(title: "Do not missionize an individual to idol worship", engText: "And all Israel shall listen and fear, and they shall no longer do any evil such as this in your midst.", hebText: "וְכָ֨ל־יִשְׂרָאֵ֔ל יִשְׁמְע֖וּ וְיִֽרָא֑וּן וְלֹֽא־יוֹסִ֣פוּ לַֽעֲשׂ֗וֹת כַּדָּבָ֥ר הָרָ֛ע הַזֶּ֖ה בְּקִרְבֶּֽךָ:", verse: "Devarim 13:12", tags: ["Negative", "Applicable", "Idolatry", "Avodah Zarah", "Devarim"]),
            Mitzvah(title: "Do not love the missionary", engText: "You shall not desire him, and you shall not hearken to him; neither shall you pity him, have mercy upon him, nor shield him", hebText: "לֹֽא־תֹאבֶ֣ה ל֔וֹ וְלֹ֥א תִשְׁמַ֖ע אֵלָ֑יו וְלֹֽא־תָח֤וֹס עֵֽינְךָ֙ עָלָ֔יו וְלֹֽא־תַחְמֹ֥ל וְלֹֽא־תְכַסֶּ֖ה עָלָֽיו:", verse: "Devarim 13:9", tags: ["Negative", "Applicable", "Idolatry", "Avodah Zarah", "Devarim"]),
            Mitzvah(title: "Do not cease hating the missionary", engText: "You shall not desire him, and you shall not hearken to him; neither shall you pity him, have mercy upon him, nor shield him", hebText: "לֹֽא־תֹאבֶ֣ה ל֔וֹ וְלֹ֥א תִשְׁמַ֖ע אֵלָ֑יו וְלֹֽא־תָח֤וֹס עֵֽינְךָ֙ עָלָ֔יו וְלֹֽא־תַחְמֹ֥ל וְלֹֽא־תְכַסֶּ֖ה עָלָֽיו:", verse: "Devarim 13:9", tags: ["Negative", "Applicable", "Idolatry", "Avodah Zarah", "Devarim"]),
            Mitzvah(title: "Do not save the missionary", engText: "You shall not desire him, and you shall not hearken to him; neither shall you pity him, have mercy upon him, nor shield him", hebText: "לֹֽא־תֹאבֶ֣ה ל֔וֹ וְלֹ֥א תִשְׁמַ֖ע אֵלָ֑יו וְלֹֽא־תָח֤וֹס עֵֽינְךָ֙ עָלָ֔יו וְלֹֽא־תַחְמֹ֥ל וְלֹֽא־תְכַסֶּ֖ה עָלָֽיו:", verse: "Devarim 13:9", tags: ["Negative", "Applicable", "Idolatry", "Avodah Zarah", "Devarim"]),
            Mitzvah(title: "Do not say anything in the missionary's defense", engText: "You shall not desire him, and you shall not hearken to him; neither shall you pity him, have mercy upon him, nor shield him", hebText: "לֹֽא־תֹאבֶ֣ה ל֔וֹ וְלֹ֥א תִשְׁמַ֖ע אֵלָ֑יו וְלֹֽא־תָח֤וֹס עֵֽינְךָ֙ עָלָ֔יו וְלֹֽא־תַחְמֹ֥ל וְלֹֽא־תְכַסֶּ֖ה עָלָֽיו:", verse: "Devarim 13:9", tags: ["Negative", "Applicable", "Idolatry", "Avodah Zarah", "Devarim"]),
            Mitzvah(title: "Do not refrain from incriminating the missionary", engText: "You shall not desire him, and you shall not hearken to him; neither shall you pity him, have mercy upon him, nor shield him", hebText: "לֹֽא־תֹאבֶ֣ה ל֔וֹ וְלֹ֥א תִשְׁמַ֖ע אֵלָ֑יו וְלֹֽא־תָח֤וֹס עֵֽינְךָ֙ עָלָ֔יו וְלֹֽא־תַחְמֹ֥ל וְלֹֽא־תְכַסֶּ֖ה עָלָֽיו:", verse: "Devarim 13:9", tags: ["Negative", "Applicable", "Idolatry", "Avodah Zarah", "Devarim"]),
            Mitzvah(title: "Do not prophesize in the name of idols", engText: "But the prophet who intentionally speaks a word in My name, which I did not command him to speak, or who speaks in the name of other gods, that prophet shall die.", hebText: "אַ֣ךְ הַנָּבִ֡יא אֲשֶׁ֣ר יָזִיד֩ לְדַבֵּ֨ר דָּבָ֜ר בִּשְׁמִ֗י אֵ֣ת אֲשֶׁ֤ר לֹֽא־צִוִּיתִיו֙ לְדַבֵּ֔ר וַֽאֲשֶׁ֣ר יְדַבֵּ֔ר בְּשֵׁ֖ם אֱלֹהִ֣ים אֲחֵרִ֑ים וּמֵ֖ת הַנָּבִ֥יא הַהֽוּא:", verse: "Devarim 18:20", tags: ["Negative", "Applicable", "Speech", "Idolatry", "Avodah Zarah", "Devarim"]),
            Mitzvah(title: "Do not listen to a false prophet", engText: "you shall not heed the words of that prophet, or that dreamer of a dream; for the Lord, your God, is testing you, to know whether you really love the Lord, your God, with all your heart and with all your soul.", hebText: "לֹ֣א תִשְׁמַ֗ע אֶל־דִּבְרֵי֙ הַנָּבִ֣יא הַה֔וּא א֛וֹ אֶל־חוֹלֵ֥ם הַֽחֲל֖וֹם הַה֑וּא כִּ֣י מְנַסֶּ֞ה יְהֹוָ֤ה אֱלֹֽהֵיכֶם֙ אֶתְכֶ֔ם לָדַ֗עַת הֲיִשְׁכֶ֤ם אֹֽהֲבִים֙ אֶת־יְהֹוָ֣ה אֱלֹֽהֵיכֶ֔ם בְּכָל־לְבַבְכֶ֖ם וּבְכָל־נַפְשְׁכֶֽם:", verse: "Devarim 13:4", tags: ["Negative", "Applicable", "Idolatry", "Avodah Zarah", "Devarim"]),
            Mitzvah(title: "Do not prophesize falsely in the name of God", engText: "But the prophet who intentionally speaks a word in My name, which I did not command him to speak, or who speaks in the name of other gods, that prophet shall die.", hebText: "אַ֣ךְ הַנָּבִ֡יא אֲשֶׁ֣ר יָזִיד֩ לְדַבֵּ֨ר דָּבָ֜ר בִּשְׁמִ֗י אֵ֣ת אֲשֶׁ֤ר לֹֽא־צִוִּיתִיו֙ לְדַבֵּ֔ר וַֽאֲשֶׁ֣ר יְדַבֵּ֔ר בְּשֵׁ֖ם אֱלֹהִ֣ים אֲחֵרִ֑ים וּמֵ֖ת הַנָּבִ֥יא הַהֽוּא:", verse: "Devarim 18:20", tags: ["Negative", "Applicable", "Speech", "Devarim"]),
            Mitzvah(title: "Do not be afraid of killing the false prophet", engText: "If the prophet speaks in the name of the Lord, and the thing does not occur and does not come about, that is the thing the Lord did not speak. The prophet has spoken it wantonly; you shall not be afraid of him.", hebText: "אֲשֶׁר֩ יְדַבֵּ֨ר הַנָּבִ֜יא בְּשֵׁ֣ם יְהֹוָ֗ה וְלֹא־יִֽהְיֶ֤ה הַדָּבָר֙ וְלֹ֣א יָבֹ֔א ה֣וּא הַדָּבָ֔ר אֲשֶׁ֥ר לֹֽא־דִבְּר֖וֹ יְהֹוָ֑ה בְּזָדוֹן֙ דִּבְּר֣וֹ הַנָּבִ֔יא לֹ֥א תָג֖וּר מִמֶּֽנּוּ:", verse: "Devarim 18:22", tags: ["Negative", "Not Applicable", "Devarim"]),
            Mitzvah(title: "Do not swear in the name of an idol", engText: "Concerning all that I have said to you you shall beware, and the name of the gods of others you shall not mention; it shall not be heard through your mouth.", hebText: "וּבְכֹ֛ל אֲשֶׁר־אָמַ֥רְתִּי אֲלֵיכֶ֖ם תִּשָּׁמֵ֑רוּ וְשֵׁ֨ם אֱלֹהִ֤ים אֲחֵרִים֙ לֹ֣א תַזְכִּ֔ירוּ לֹ֥א יִשָּׁמַ֖ע עַל־פִּֽיךָ:", verse: "Shemot 23:13", tags: ["Negative", "Applicable", "Idolatry", "Avodah Zarah", "Speech", "Shemot"]),
            Mitzvah(title: "Do not perform Ov (medium)", engText: "You shall not turn to [the sorcery of] Ov or Yid'oni; you shall not seek [these and thereby] defile yourselves through them. I am the Lord, your God.", hebText: "אַל־תִּפְנ֤וּ אֶל־הָֽאֹבֹת֙ וְאֶל־הַיִּדְּעֹנִ֔ים אַל־תְּבַקְשׁ֖וּ לְטָמְאָ֣ה בָהֶ֑ם אֲנִ֖י יְהוָֹ֥ה אֱלֹֽהֵיכֶֽם:", verse: "Vayikra 19:31", tags: ["Negative", "Applicable", "Avodah Zarah", "Vayikra"]),
            Mitzvah(title: "Do not perform Yidoni (magical seer)", engText: "You shall not turn to [the sorcery of] Ov or Yid'oni; you shall not seek [these and thereby] defile yourselves through them. I am the Lord, your God.", hebText: "אַל־תִּפְנ֤וּ אֶל־הָֽאֹבֹת֙ וְאֶל־הַיִּדְּעֹנִ֔ים אַל־תְּבַקְשׁ֖וּ לְטָמְאָ֣ה בָהֶ֑ם אֲנִ֖י יְהוָֹ֥ה אֱלֹֽהֵיכֶֽם:", verse: "Vayikra 19:31", tags: ["Negative", "Applicable", "Avodah Zarah", "Vayikra"]),
            Mitzvah(title: "Do not pass your children through the fire for Moloch", engText: "And you shall not give any of your offspring to pass through for Molech. And you shall not profane the Name of your God. I am the Lord.", hebText: "וּמִזַּרְעֲךָ֥ לֹֽא־תִתֵּ֖ן לְהַֽעֲבִ֣יר לַמֹּ֑לֶךְ וְלֹ֧א תְחַלֵּ֛ל אֶת־שֵׁ֥ם אֱלֹהֶ֖יךָ אֲנִ֥י יְהוָֹֽה:", verse: "Vayikra 18:21", tags: ["Negative", "Applicable", "Children", "Idolatry", "Avodah Zarah", "Vayikra"]),
            Mitzvah(title: "Do not erect a column in a public place of worship", engText: "And you shall not set up for yourself a monument, which the Lord, your God hates.", hebText: "וְלֹֽא־תָקִ֥ים לְךָ֖ מַצֵּבָ֑ה אֲשֶׁ֥ר שָׂנֵ֖א יְהֹוָ֥ה אֱלֹהֶֽיךָ:", verse: "Devarim 16:22", tags: ["Negative", "Applicable", "Avodah Zarah", "Devarim"]),
            Mitzvah(title: "Do not bow down on smooth stone", engText: "You shall not make idols for yourselves, nor shall you set up a statue or a monument for yourselves. And in your land you shall not place a pavement stone on which to prostrate yourselves, for I am the Lord, your God.", hebText: "לֹא־תַֽעֲשׂ֨וּ לָכֶ֜ם אֱלִילִ֗ם וּפֶ֤סֶל וּמַצֵּבָה֙ לֹֽא־תָקִ֣ימוּ לָכֶ֔ם וְאֶ֣בֶן מַשְׂכִּ֗ית לֹ֤א תִתְּנוּ֙ בְּאַרְצְכֶ֔ם לְהִשְׁתַּֽחֲוֹ֖ת עָלֶ֑יהָ כִּ֛י אֲנִ֥י יְהֹוָ֖ה אֱלֹֽהֵיכֶֽם:", verse: "Vayikra 26:1", tags: ["Negative", "Applicable", "Idolatry", "Vayikra", "Avodah Zarah"]),
            Mitzvah(title: "Do not plant a tree in the temple courtyard", engText: "You shall not plant for yourself an asherah, [or] any tree, near the altar of the Lord, your God, which you shall make for yourself.", hebText: "לֹֽא־תִטַּ֥ע לְךָ֛ אֲשֵׁרָ֖ה כָּל־עֵ֑ץ אֵ֗צֶל מִזְבַּ֛ח יְהֹוָ֥ה אֱלֹהֶ֖יךָ אֲשֶׁ֥ר תַּֽעֲשֶׂה־לָּֽךְ:", verse: "Devarim 16:21", tags: ["Negative", "Not Applicable", "Idolatry", "Holy Temple", "Avodah Zarah", "Devarim"]),
            Mitzvah(title: "Destroy idols and their accessories", engText: "You shall utterly destroy from all the places where the nations, that you shall possess, worshipped their gods, upon the lofty mountains and upon the hills, and under every lush tree.", hebText: "אַבֵּ֣ד תְּאַבְּד֠וּן אֶת־כָּל־הַמְּקֹמ֞וֹת אֲשֶׁ֧ר עָֽבְדוּ־שָׁ֣ם הַגּוֹיִ֗ם אֲשֶׁ֥ר אַתֶּ֛ם יֹֽרְשִׁ֥ים אֹתָ֖ם אֶת־אֱלֹֽהֵיהֶ֑ם עַל־הֶֽהָרִ֤ים הָֽרָמִים֙ וְעַל־הַגְּבָע֔וֹת וְתַ֖חַת כָּל־עֵ֥ץ רַֽעֲנָֽן:", verse: "Devarim 12:2", tags: ["Positive", "Applicable", "Idolatry", "Avodah Zarah", "Devarim", "Conquest"]),
            Mitzvah(title: "Do not derive benefit from idols or their accessories", engText: "Nor should you bring an abomination into your house, lest you are to be destroyed like it, but you shall utterly detest it, and you shall utterly abhor it; for it is to be destroyed.", hebText: "וְלֹֽא־תָבִ֤יא תֽוֹעֵבָה֙ אֶל־בֵּיתֶ֔ךָ וְהָיִ֥יתָ חֵ֖רֶם כָּמֹ֑הוּ שַׁקֵּ֧ץ | תְּשַׁקְּצֶ֛נּוּ וְתַעֵ֥ב | תְּתַֽעֲבֶ֖נּוּ כִּי־חֵ֥רֶם הֽוּא:", verse: "Devarim 7:26", tags: ["Negative", "Applicable", "Idolatry", "Avodah Zarah", "Devarim"]),
            Mitzvah(title: "Do not derive benefit from the ornaments of idols", engText: "The graven images of their gods you will burn with fire; you shall not covet the silver or gold that is upon them and take it for yourself, lest you be ensnared by it, for it is an abomination to the Lord, your God.", hebText: "סִילֵ֥י אֱלֹֽהֵיהֶ֖ם תִּשְׂרְפ֣וּן בָּאֵ֑שׁ לֹֽא־תַחְמֹד֩ כֶּ֨סֶף וְזָהָ֤ב עֲלֵיהֶם֙ וְלָֽקַחְתָּ֣ לָ֔ךְ פֶּ֚ן תִּוָּקֵ֣שׁ בּ֔וֹ כִּ֧י תֽוֹעֲבַ֛ת יְהֹוָ֥ה אֱלֹהֶ֖יךָ הֽוּא:", verse: "Devarim 7:25", tags: ["Negative", "Applicable", "Idolatry", "Devarim"]),
            Mitzvah(title: "Do not make covenants with idolaters", engText: "And the Lord, your God, will deliver them to you, and you shall smite them. You shall utterly destroy them; neither shall you make a covenant with them, nor be gracious to them.", hebText: "וּנְתָנָ֞ם יְהֹוָ֧ה אֱלֹהֶ֛יךָ לְפָנֶ֖יךָ וְהִכִּיתָ֑ם הַֽחֲרֵ֤ם תַּֽחֲרִים֙ אֹתָ֔ם לֹֽא־תִכְרֹ֥ת לָהֶ֛ם בְּרִ֖ית וְלֹ֥א תְחָנֵּֽם:", verse: "Devarim 7:2", tags: ["Negative", "Applicable", "Idolatry", "Devarim", "Conquest"]),
            Mitzvah(title: "Do not show favor to the idolaters", engText: "And the Lord, your God, will deliver them to you, and you shall smite them. You shall utterly destroy them; neither shall you make a covenant with them, nor be gracious to them.", hebText: "וּנְתָנָ֞ם יְהֹוָ֧ה אֱלֹהֶ֛יךָ לְפָנֶ֖יךָ וְהִכִּיתָ֑ם הַֽחֲרֵ֤ם תַּֽחֲרִים֙ אֹתָ֔ם לֹֽא־תִכְרֹ֥ת לָהֶ֛ם בְּרִ֖ית וְלֹ֥א תְחָנֵּֽם:", verse: "Devarim 7:2", tags: ["Negative", "Applicable", "Idolatry", "Devarim", "Conquest"]),
            Mitzvah(title: "Do not let the idolater dwell in the land of Israel", engText: "They shall not dwell in your land, lest they cause you to sin against Me, that you will worship their gods, which will be a snare for you.", hebText: "לֹ֤א יֵֽשְׁבוּ֙ בְּאַרְצְךָ֔ פֶּן־יַֽחֲטִ֥יאוּ אֹֽתְךָ֖ לִ֑י כִּ֤י תַֽעֲבֹד֙ אֶת־אֱלֹ֣הֵיהֶ֔ם כִּי־יִֽהְיֶ֥ה לְךָ֖ לְמוֹקֵֽשׁ:", verse: "Shemot 23:33", tags: ["Negative", "Not Applicable", "Conquest", "Idolatry", "Avodah Zarah", "Shemot"]),
            Mitzvah(title: "Do not imitate in customs or clothing the nations which God sent away from before Israel", engText: "You shall not follow the practices of the nation that I am sending away from before you, for they committed all these [sins], and I was disgusted with them.", hebText: "וְלֹ֤א תֵֽלְכוּ֙ בְּחֻקֹּ֣ת הַגּ֔וֹי אֲשֶׁר־אֲנִ֥י מְשַׁלֵּ֖חַ מִפְּנֵיכֶ֑ם כִּ֤י אֶת־כָּל־אֵ֨לֶּה֙ עָשׂ֔וּ וָֽאָקֻ֖ץ בָּֽם:", verse: "Vayikra 20:23", tags: ["Negative", "Applicable", "Conquest", "Idolatry", "Avodah Zarah", "Vayikra"]),
            Mitzvah(title: "Do not be superstitious", engText: "You shall not eat over the blood. You shall not act on the basis of omens or lucky hours.", hebText: "לֹ֥א תֹֽאכְל֖וּ עַל־הַדָּ֑ם לֹ֥א תְנַֽחֲשׁ֖וּ וְלֹ֥א תְעוֹנֵֽנוּ:", verse: "Vayikra 19:26", tags: ["Negative", "Applicable", "Avodah Zarah", "Vayikra"]),
            Mitzvah(title: "Do not go into a trance to forsee events", engText: "There shall not be found among you anyone who passes his son or daughter through fire, a soothsayer, a diviner of [auspicious] times, one who interprets omens, or a sorcerer", hebText: "לֹֽא־יִמָּצֵ֣א בְךָ֔ מַֽעֲבִ֥יר בְּנֽוֹ־וּבִתּ֖וֹ בָּאֵ֑שׁ קֹסֵ֣ם קְסָמִ֔ים מְעוֹנֵ֥ן וּמְנַחֵ֖שׁ וּמְכַשֵּֽׁף:", verse: "Devarim 18:10", tags: ["Negative", "Applicable", "Avodah Zarah", "Devarim"]),
            Mitzvah(title: "Do not engage in astrology", engText: "You shall not eat over the blood. You shall not act on the basis of omens or lucky hours.", hebText: "לֹ֥א תֹֽאכְל֖וּ עַל־הַדָּ֑ם לֹ֥א תְנַֽחֲשׁ֖וּ וְלֹ֥א תְעוֹנֵֽנוּ:", verse: "Vayikra 19:26", tags: ["Negative", "Applicable", "Avodah Zarah", "Vayikra"]),
            Mitzvah(title: "Do not mutter incantations", engText: "[There shall not be found among you]... or a charmer, a pithom sorcerer, a yido'a sorcerer, or a necromancer.", hebText: "[לֹֽא־יִמָּצֵ֣א בְךָ֔]... וְחֹבֵ֖ר חָ֑בֶר וְשֹׁאֵ֥ל אוֹב֙ וְיִדְּעֹנִ֔י וְדֹרֵ֖שׁ אֶל־הַמֵּתִֽים:", verse: "Devarim 18:11", tags: ["Negative", "Applicable", "Avodah Zarah", "Devarim", "Speech"]),
            Mitzvah(title: "Do not attempt to engage the dead in conversation", engText: "[There shall not be found among you]... or a charmer, a pithom sorcerer, a yido'a sorcerer, or a necromancer.", hebText: "[לֹֽא־יִמָּצֵ֣א בְךָ֔]... וְחֹבֵ֖ר חָ֑בֶר וְשֹׁאֵ֥ל אוֹב֙ וְיִדְּעֹנִ֔י וְדֹרֵ֖שׁ אֶל־הַמֵּתִֽים:", verse: "Devarim 18:11", tags: ["Negative", "Applicable", "Avodah Zarah", "Devarim"]),
            Mitzvah(title: "Do not consult the Ov", engText: "[There shall not be found among you]... or a charmer, a pithom sorcerer, a yido'a sorcerer, or a necromancer.", hebText: "[לֹֽא־יִמָּצֵ֣א בְךָ֔]... וְחֹבֵ֖ר חָ֑בֶר וְשֹׁאֵ֥ל אוֹב֙ וְיִדְּעֹנִ֔י וְדֹרֵ֖שׁ אֶל־הַמֵּתִֽים:", verse: "Devarim 18:11", tags: ["Negative", "Applicable", "Avodah Zarah", "Devarim"]),
            Mitzvah(title: "Do not consult the Yidoni", engText: "[There shall not be found among you]... or a charmer, a pithom sorcerer, a yido'a sorcerer, or a necromancer.", hebText: "[לֹֽא־יִמָּצֵ֣א בְךָ֔]... וְחֹבֵ֖ר חָ֑בֶר וְשֹׁאֵ֥ל אוֹב֙ וְיִדְּעֹנִ֔י וְדֹרֵ֖שׁ אֶל־הַמֵּתִֽים:", verse: "Devarim 18:11", tags: ["Negative", "Applicable", "Avodah Zarah", "Devarim"]),
            Mitzvah(title: "Do not perform acts of sorcery", engText: "There shall not be found among you anyone who passes his son or daughter through fire, a soothsayer, a diviner of [auspicious] times, one who interprets omens, or a sorcerer,", hebText: "לֹֽא־יִמָּצֵ֣א בְךָ֔ מַֽעֲבִ֥יר בְּנֽוֹ־וּבִתּ֖וֹ בָּאֵ֑שׁ קֹסֵ֣ם קְסָמִ֔ים מְעוֹנֵ֥ן וּמְנַחֵ֖שׁ וּמְכַשֵּֽׁף:", verse: "Devarim 18:10", tags: ["Negative", "Applicable", "Avodah Zarah", "Devarim"]),
            Mitzvah(title: "Men must not shave the sides of their heads", engText: "You shall not round off the corner of your head, and you shall not destroy the edge of your beard.", hebText: "לֹ֣א תַקִּ֔פוּ פְּאַ֖ת רֹֽאשְׁכֶ֑ם וְלֹ֣א תַשְׁחִ֔ית אֵ֖ת פְּאַ֥ת זְקָנֶֽךָ:", verse: "Vayikra 19:27", tags: ["Negative", "Applicable", "Vayikra"]),
            Mitzvah(title: "Do not shave the beard with a razor", engText: "You shall not round off the corner of your head, and you shall not destroy the edge of your beard.", hebText: "לֹ֣א תַקִּ֔פוּ פְּאַ֖ת רֹֽאשְׁכֶ֑ם וְלֹ֣א תַשְׁחִ֔ית אֵ֖ת פְּאַ֥ת זְקָנֶֽךָ:", verse: "Vayikra 19:27", tags: ["Negative", "Applicable", "Vayikra"]),
            Mitzvah(title: "Men must not wear women's clothing", engText: "A man's attire shall not be on a woman, nor may a man wear a woman's garment because whoever does these [things] is an abomination to the Lord, your God.", hebText: "לֹא־יִֽהְיֶ֤ה כְלִי־גֶ֨בֶר֙ עַל־אִשָּׁ֔ה וְלֹֽא־יִלְבַּ֥שׁ גֶּ֖בֶר שִׂמְלַ֣ת אִשָּׁ֑ה כִּ֧י תֽוֹעֲבַ֛ת יְהֹוָ֥ה אֱלֹהֶי֖ךָ כָּל־עֹ֥שֵׂה אֵֽלֶּה:", verse: "Devarim 22:5", tags: ["Negative", "Applicable", "Devarim"]),
            Mitzvah(title: "Women must not wear men's clothing", engText: "A man's attire shall not be on a woman, nor may a man wear a woman's garment because whoever does these [things] is an abomination to the Lord, your God.", hebText: "לֹא־יִֽהְיֶ֤ה כְלִי־גֶ֨בֶר֙ עַל־אִשָּׁ֔ה וְלֹֽא־יִלְבַּ֥שׁ גֶּ֖בֶר שִׂמְלַ֣ת אִשָּׁ֑ה כִּ֧י תֽוֹעֲבַ֛ת יְהֹוָ֥ה אֱלֹהֶי֖ךָ כָּל־עֹ֥שֵׂה אֵֽלֶּה:", verse: "Devarim 22:5", tags: ["Negative", "Applicable", "Devarim"]),
            Mitzvah(title: "Do not tattoo the skin", engText: "You shall not make cuts in your flesh for a person [who died]. You shall not etch a tattoo on yourselves. I am the Lord.", hebText: "וְשֶׂ֣רֶט לָנֶ֗פֶשׁ לֹ֤א תִתְּנוּ֙ בִּבְשַׂרְכֶ֔ם וּכְתֹ֣בֶת קַֽעֲקַ֔ע לֹ֥א תִתְּנ֖וּ בָּכֶ֑ם אֲנִ֖י יְהוָֹֽה:", verse: "Vayikra 19:28", tags: ["Negative", "Applicable", "Vayikra"]),
            Mitzvah(title: "Do not tear the skin in mourning", engText: "You are children of the Lord, your God. You shall neither cut yourselves nor make any baldness between your eyes for the dead.", hebText: "בָּנִ֣ים אַתֶּ֔ם לַֽיהֹוָ֖ה אֱלֹֽהֵיכֶ֑ם לֹ֣א תִתְגֹּֽדְד֗וּ וְלֹֽא־תָשִׂ֧ימוּ קָרְחָ֛ה בֵּ֥ין עֵֽינֵיכֶ֖ם לָמֵֽת:", verse: "Devarim 14:1", tags: ["Negative", "Applicable", "Devarim"]),
            Mitzvah(title: "Do not make a bald spot in mourning", engText: "You are children of the Lord, your God. You shall neither cut yourselves nor make any baldness between your eyes for the dead.", hebText: "בָּנִ֣ים אַתֶּ֔ם לַֽיהֹוָ֖ה אֱלֹֽהֵיכֶ֑ם לֹ֣א תִתְגֹּֽדְד֗וּ וְלֹֽא־תָשִׂ֧ימוּ קָרְחָ֛ה בֵּ֥ין עֵֽינֵיכֶ֖ם לָמֵֽת:", verse: "Devarim 14:1", tags: ["Negative", "Applicable", "Devarim"]),
            Mitzvah(title: "Repent and confess wrongdoing", engText: "they shall confess the sin they committed, and make restitution for the principal amount of his guilt, add its fifth to it, and give it to the one against whom he was guilty.", hebText: "וְהִתְוַדּ֗וּ אֶת־חַטָּאתָם֘ אֲשֶׁ֣ר עָשׂוּ֒ וְהֵשִׁ֤יב אֶת־אֲשָׁמוֹ֙ בְּרֹאשׁ֔וֹ וַֽחֲמִֽישִׁת֖וֹ יֹסֵ֣ף עָלָ֑יו וְנָתַ֕ן לַֽאֲשֶׁ֖ר אָשַׁ֥ם לֽוֹ:", verse: "BaMidbar 5:7", tags: ["Positive", "Applicable", "BaMidbar"]),
            Mitzvah(title: "Say the Shema twice daily", engText: "And you shall teach them to your sons and speak of them when you sit in your house, and when you walk on the way, and when you lie down and when you rise up.", hebText: "וְשִׁנַּנְתָּ֣ם לְבָנֶ֔יךָ וְדִבַּרְתָּ֖ בָּ֑ם בְּשִׁבְתְּךָ֤ בְּבֵיתֶ֨ךָ֙ וּבְלֶכְתְּךָ֣ בַדֶּ֔רֶךְ וּבְשָׁכְבְּךָ֖ וּבְקוּמֶֽךָ:", verse: "Devarim 6:7", tags: ["Positive", "Applicable", "Speech", "Devarim"]),
            Mitzvah(title: "Serve the Almighty with prayer daily", engText: "And you shall worship the Lord, your God, and He will bless your food and your drink, and I will remove illness from your midst.", hebText: "וַֽעֲבַדְתֶּ֗ם אֵ֚ת יְהֹוָ֣ה אֱלֹֽהֵיכֶ֔ם וּבֵרַ֥ךְ אֶת־לַחְמְךָ֖ וְאֶת־מֵימֶ֑יךָ וַֽהֲסִֽרֹתִ֥י מַֽחֲלָ֖ה מִקִּרְבֶּֽךָ:", verse: "Shemot 23:25", tags: ["Positive", "Applicable", "Speech", "Shemot"]),
            Mitzvah(title: "The Kohanim must bless the Jewish nation daily", engText: "Speak to Aaron and his sons, saying: This is how you shall bless the children of Israel, saying to them:", hebText: "דַּבֵּ֤ר אֶל־אַֽהֲרֹן֙ וְאֶל־בָּנָ֣יו לֵאמֹ֔ר כֹּ֥ה תְבָֽרֲכ֖וּ אֶת־בְּנֵ֣י יִשְׂרָאֵ֑ל אָמ֖וֹר לָהֶֽם:", verse: "BaMidbar 6:23", tags: ["Positive", "Not Applicable", "Speech", "Levitical", "BaMidbar"]),
            Mitzvah(title: "Wear Tefillin on the head", engText: "And you shall bind them for a sign upon your hand, and they shall be for ornaments between your eyes.", hebText: "וּקְשַׁרְתָּ֥ם לְא֖וֹת עַל־יָדֶ֑ךָ וְהָי֥וּ לְטֹֽטָפֹ֖ת בֵּ֥ין עֵינֶֽיךָ:", verse: "Devarim 6:8", tags: ["Positive", "Applicable", "Devarim"]),
            Mitzvah(title: "Bind Tefillin on the arm", engText: "And you shall bind them for a sign upon your hand, and they shall be for ornaments between your eyes.", hebText: "וּקְשַׁרְתָּ֥ם לְא֖וֹת עַל־יָדֶ֑ךָ וְהָי֥וּ לְטֹֽטָפֹ֖ת בֵּ֥ין עֵינֶֽיךָ:", verse: "Devarim 6:8", tags: ["Positive", "Applicable", "Devarim"]),
            Mitzvah(title: "Put a Mezuzah on each doorpost", engText: "And you shall inscribe them upon the doorposts of your house and upon your gates.", hebText: "וּכְתַבְתָּ֛ם עַל־מְזֻז֥וֹת בֵּיתֶ֖ךָ וּבִשְׁעָרֶֽיךָ:", verse: "Devarim 6:9", tags: ["Positive", "Applicable", "Devarim"]),
            Mitzvah(title: "Write a Sefer Torah", engText: "And now, write for yourselves this song, and teach it to the Children of Israel. Place it into their mouths, in order that this song will be for Me as a witness for the children of Israel.", hebText: "וְעַתָּ֗ה כִּתְב֤וּ לָכֶם֙ אֶת־הַשִּׁירָ֣ה הַזֹּ֔את וְלַמְּדָ֥הּ אֶת־בְּנֵֽי־יִשְׂרָאֵ֖ל שִׂימָ֣הּ בְּפִיהֶ֑ם לְמַ֨עַן תִּֽהְיֶה־לִּ֜י הַשִּׁירָ֥ה הַזֹּ֛את לְעֵ֖ד בִּבְנֵ֥י יִשְׂרָאֵֽל:", verse: "Devarim 31:19", tags: ["Positive", "Applicable", "Devarim"]),
            Mitzvah(title: "A king must have a separate Sefer Torah for himself", engText: "And it will be, when he sits upon his royal throne, that he shall write for himself two copies of this Torah on a scroll from [that Torah which is] before the Levitic kohanim.", hebText: "וְהָיָ֣ה כְשִׁבְתּ֔וֹ עַ֖ל כִּסֵּ֣א מַמְלַכְתּ֑וֹ וְכָ֨תַב ל֜וֹ אֶת־מִשְׁנֵ֨ה הַתּוֹרָ֤ה הַזֹּאת֙ עַל־סֵ֔פֶר מִלִּפְנֵ֖י הַכֹּֽהֲנִ֥ים הַֽלְוִיִּֽם:", verse: "Devarim 17:18", tags: ["Positive", "Not Applicable", "Devarim"]),
            Mitzvah(title: "Have Tzitzit on four-cornered garments", engText: "Speak to the children of Israel and you shall say to them that they shall make for themselves fringes on the corners of their garments, throughout their generations, and they shall affix a thread of sky blue [wool] on the fringe of each corner.", hebText: "דַּבֵּ֞ר אֶל־בְּנֵ֤י יִשְׂרָאֵל֙ וְאָֽמַרְתָּ֣ אֲלֵהֶ֔ם וְעָשׂ֨וּ לָהֶ֥ם צִיצִ֛ת עַל־כַּנְפֵ֥י בִגְדֵיהֶ֖ם לְדֹֽרֹתָ֑ם וְנָֽתְנ֛וּ עַל־צִיצִ֥ת הַכָּנָ֖ף פְּתִ֥יל תְּכֵֽלֶת:", verse: "BaMidbar 15:38", tags: ["Positive", "Applicable", "BaMidbar"]),
            Mitzvah(title: "Bless the Almighty after eating", engText: "And you will eat and be sated, and you shall bless the Lord, your God, for the good land He has given you.", hebText: "וְאָֽכַלְתָּ֖ וְשָׂבָ֑עְתָּ וּבֵֽרַכְתָּ֙ אֶת־יְהֹוָ֣ה אֱלֹהֶ֔יךָ עַל־הָאָ֥רֶץ הַטֹּבָ֖ה אֲשֶׁ֥ר נָֽתַן־לָֽךְ:", verse: "Devarim 8:10", tags: ["Positive", "Applicable", "Speech", "Devarim"]),
            Mitzvah(title: "Circumcise all males on the 8th day after birth", engText: "And on the eighth day, the flesh of his foreskin shall be circumcised.", hebText: "וּבַיּ֖וֹם הַשְּׁמִינִ֑י יִמּ֖וֹל בְּשַׂ֥ר עָרְלָתֽוֹ:", verse: "Vayikra 12:3", tags: ["Positive", "Applicable", "Children", "Vayikra"]),
            Mitzvah(title: "Rest on the seventh day", engText: "Six days you may do your work, but on the seventh day you shall rest, in order that your ox and your donkey shall rest, and your maidservant's son and the stranger shall be refreshed.", hebText: "שֵׁ֤שֶׁת יָמִים֙ תַּֽעֲשֶׂ֣ה מַֽעֲשֶׂ֔יךָ וּבַיּ֥וֹם הַשְּׁבִיעִ֖י תִּשְׁבֹּ֑ת לְמַ֣עַן יָנ֗וּחַ שֽׁוֹרְךָ֙ וַֽחֲמֹרֶ֔ךָ וְיִנָּפֵ֥שׁ בֶּן־אֲמָֽתְךָ֖ וְהַגֵּֽר:", verse: "Shemot 23:12", tags: ["Positive", "Applicable", "Business", "Shabbat", "Shemot"]),
            Mitzvah(title: "Do not do prohibited labor on the seventh day", engText: "but the seventh day is a Sabbath to the Lord, your God; you shall perform no labor, neither you, your son, your daughter, your manservant, your maidservant, your beast, nor your stranger who is in your cities.", hebText: "וְי֨וֹם הַשְּׁבִיעִ֜י שַׁבָּ֣ת | לַֽיהֹוָ֣ה אֱלֹהֶ֗יךָ לֹ֣א תַֽעֲשֶׂ֣ה כָל־מְלָאכָ֡ה אַתָּ֣ה | וּבִנְךָ֣־וּ֠בִתֶּךָ עַבְדְּךָ֨ וַֽאֲמָֽתְךָ֜ וּבְהֶמְתֶּ֗ךָ וְגֵֽרְךָ֙ אֲשֶׁ֣ר בִּשְׁעָרֶ֔יךָ:", verse: "Shemot 20:10", tags: ["Negative", "Applicable", "Shabbat", "Business", "Shemot"]),
            Mitzvah(title: "The court must not inflict punishment on Shabbat", engText: "Six days work may be done, but on the seventh day you shall have sanctity, a day of complete rest to the Lord; whoever performs work thereon [on this day] shall be put to death. 3You shall not kindle fire in any of your dwelling places on the Sabbath day.", hebText: "שֵׁ֣שֶׁת יָמִים֘ תֵּֽעָשֶׂ֣ה מְלָאכָה֒ וּבַיּ֣וֹם הַשְּׁבִיעִ֗י יִֽהְיֶ֨ה לָכֶ֥ם קֹ֛דֶשׁ שַׁבַּ֥ת שַׁבָּת֖וֹן לַֽיהֹוָ֑ה כָּל־הָֽעֹשֶׂ֥ה ב֛וֹ מְלָאכָ֖ה יוּמָֽת: גלֹֽא־תְבַֽעֲר֣וּ אֵ֔שׁ בְּכֹ֖ל מֽשְׁבֹֽתֵיכֶ֑ם בְּי֖וֹם הַשַּׁבָּֽת:", verse: "Shemot 35:2-3", tags: ["Negative", "Shabbat", "Courts", "Not Applicable", "Shemot"]),
            Mitzvah(title: "Do not walk more than 2000 cubits outside the city boundary on Shabbat", engText: "See that the Lord has given you the Sabbath. Therefore, on the sixth day, He gives you bread for two days. Let each man remain in his place; let no man leave his place on the seventh day.", hebText: "רְא֗וּ כִּֽי־יְהֹוָה֘ נָתַ֣ן לָכֶ֣ם הַשַּׁבָּת֒ עַל־כֵּ֠ן ה֣וּא נֹתֵ֥ן לָכֶ֛ם בַּיּ֥וֹם הַשִּׁשִּׁ֖י לֶ֣חֶם יוֹמָ֑יִם שְׁב֣וּ | אִ֣ישׁ תַּחְתָּ֗יו אַל־יֵ֥צֵא אִ֛ישׁ מִמְּקֹמ֖וֹ בַּיּ֥וֹם הַשְּׁבִיעִֽי:", verse: "Shemot 16:29", tags: ["Negative", "Applicable", "Shabbat", "Shemot"]),
            Mitzvah(title: "Sanctify Shabbat with Kidush and Havdalah", engText: "Remember the Sabbath day to sanctify it.", hebText: "זָכוֹר֩ אֶת־י֨וֹם הַשַּׁבָּ֜ת לְקַדְּשׁ֗וֹ:", verse: "Shemot 20:8", tags: ["Positive", "Applicable", "Ten Commandments", "Shabbat", "Shemot"]),
            Mitzvah(title: "Rest from prohibited labor on Yom Kippur", engText: "It is a complete day of rest for you, and you shall afflict yourselves. On the ninth of the month in the evening, from evening to evening, you shall observe your rest day.", hebText: "שַׁבַּ֨ת שַׁבָּת֥וֹן הוּא֙ לָכֶ֔ם וְעִנִּיתֶ֖ם אֶת־נַפְשֹֽׁתֵיכֶ֑ם בְּתִשְׁעָ֤ה לַחֹ֨דֶשׁ֙ בָּעֶ֔רֶב מֵעֶ֣רֶב עַד־עֶ֔רֶב תִּשְׁבְּת֖וּ שַׁבַּתְּכֶֽם:", verse: "Vayikra 23:32", tags: ["Positive", "Applicable", "Yom Kippur", "Business", "Holidays", "Vayikra"]),
            Mitzvah(title: "Do not do prohibited labor on Yom Kippur", engText: "You shall not perform any work. [This is] an eternal statute throughout your generations in all your dwelling places.", hebText: "כָּל־מְלָאכָ֖ה לֹ֣א תַֽעֲשׂ֑וּ חֻקַּ֤ת עוֹלָם֙ לְדֹרֹ֣תֵיכֶ֔ם בְּכֹ֖ל מֽשְׁבֹֽתֵיכֶֽם:", verse: "Vayikra 23:31", tags: ["Negative", "Applicable", "Yom Kippur", "Business", "Holidays", "Vayikra"]),
            Mitzvah(title: "Afflict yourself on Yom Kippur", engText: "And [all this] shall be as an eternal statute for you; in the seventh month, on the tenth of the month, you shall afflict yourselves, and you shall not do any work neither the native nor the stranger who dwells among you.", hebText: "וְהָֽיְתָ֥ה לָכֶ֖ם לְחֻקַּ֣ת עוֹלָ֑ם בַּחֹ֣דֶשׁ הַ֠שְּׁבִיעִ֠י בֶּֽעָשׂ֨וֹר לַחֹ֜דֶשׁ תְּעַנּ֣וּ אֶת־נַפְשֹֽׁתֵיכֶ֗ם וְכָל־מְלָאכָה֙ לֹ֣א תַֽעֲשׂ֔וּ הָ֣אֶזְרָ֔ח וְהַגֵּ֖ר הַגָּ֥ר בְּתֽוֹכְכֶֽם:", verse: "Vayikra 16:29", tags: ["Positive", "Applicable", "Yom Kippur", "Holidays", "Vayikra"]),
            Mitzvah(title: "Do not eat or drink on Yom Kippur", engText: "For any person who will not be afflicted on that very day, shall be cut off from its people.", hebText: "כִּ֤י כָל־הַנֶּ֨פֶשׁ֙ אֲשֶׁ֣ר לֹֽא־תְעֻנֶּ֔ה בְּעֶ֖צֶם הַיּ֣וֹם הַזֶּ֑ה וְנִכְרְתָ֖ה מֵֽעַמֶּֽיהָ:", verse: "Vayikra 23:29", tags: ["Negative", "Applicable", "Yom Kippur", "Holidays", "Vayikra"]),
            Mitzvah(title: "Rest on the first day of Passover", engText: "On the first day, there shall be a holy occasion for you; you shall not perform any work of labor.", hebText: "בַּיּוֹם֙ הָֽרִאשׁ֔וֹן מִקְרָא־קֹ֖דֶשׁ יִֽהְיֶ֣ה לָכֶ֑ם כָּל־מְלֶ֥אכֶת עֲבֹדָ֖ה לֹ֥א תַֽעֲשֽׂוּ:", verse: "Vayikra 23:7", tags: ["Positive", "Applicable", "Passover", "Business", "Holidays", "Vayikra"]),
            Mitzvah(title: "Do not do prohibited labor on the first day of Passover", engText: "On the first day, there shall be a holy occasion for you; you shall not perform any work of labor.", hebText: "בַּיּוֹם֙ הָֽרִאשׁ֔וֹן מִקְרָא־קֹ֖דֶשׁ יִֽהְיֶ֣ה לָכֶ֑ם כָּל־מְלֶ֥אכֶת עֲבֹדָ֖ה לֹ֥א תַֽעֲשֽׂוּ:", verse: "Vayikra 23:7", tags: ["Negative", "Applicable", "Passover", "Business", "Holidays", "Vayikra"]),
            Mitzvah(title: "Rest on the seventh day of Passover", engText: "And you shall bring a fire offering to the Lord for a seven day period. On the seventh day, there shall be a holy occasion; you shall not perform any work of labor.", hebText: "וְהִקְרַבְתֶּ֥ם אִשֶּׁ֛ה לַֽיהֹוָ֖ה שִׁבְעַ֣ת יָמִ֑ים בַּיּ֤וֹם הַשְּׁבִיעִי֙ מִקְרָא־קֹ֔דֶשׁ כָּל־מְלֶ֥אכֶת עֲבֹדָ֖ה לֹ֥א תַֽעֲשֽׂוּ:", verse: "Vayikra 23:8", tags: ["Positive", "Applicable", "Passover", "Business", "Holidays", "Vayikra"]),
            Mitzvah(title: "Do not do prohibited labor on the seventh day of Passover", engText: "And you shall bring a fire offering to the Lord for a seven day period. On the seventh day, there shall be a holy occasion; you shall not perform any work of labor.", hebText: "וְהִקְרַבְתֶּ֥ם אִשֶּׁ֛ה לַֽיהֹוָ֖ה שִׁבְעַ֣ת יָמִ֑ים בַּיּ֤וֹם הַשְּׁבִיעִי֙ מִקְרָא־קֹ֔דֶשׁ כָּל־מְלֶ֥אכֶת עֲבֹדָ֖ה לֹ֥א תַֽעֲשֽׂוּ:", verse: "Vayikra 23:8", tags: ["Negative", "Applicable", "Passover", "Business", "Holidays", "Vayikra"]),
            Mitzvah(title: "Rest on Shavuot", engText: "And you shall designate on this very day a holy occasion it shall be for you; you shall not perform any work of labor. [This is] an eternal statute in all your dwelling places throughout your generations.", hebText: "וּקְרָאתֶ֞ם בְּעֶ֣צֶם | הַיּ֣וֹם הַזֶּ֗ה מִקְרָא־קֹ֨דֶשׁ֙ יִֽהְיֶ֣ה לָכֶ֔ם כָּל־מְלֶ֥אכֶת עֲבֹדָ֖ה לֹ֣א תַֽעֲשׂ֑וּ חֻקַּ֥ת עוֹלָ֛ם בְּכָל־מֽוֹשְׁבֹ֥תֵיכֶ֖ם לְדֹרֹֽתֵיכֶֽם:", verse: "Vayikra 23:21", tags: ["Positive", "Applicable", "Shavuot", "Business", "Holidays", "Vayikra"]),
            
        ]
    }
    
    enum Filter {
        case positive, negative, prayer, tenCommandments, passover, sukkot, roshHaShana, yomKippur, speech, blasphemy, lashonHaRa, shavuot, business, intimateRelations, forbiddenRelations, idolatry, kashrut, robbery, assault, children, courts, holidays, shabbat, levitical, holyTemple, conquest, applicable, unApplicable
    }
    
    static let filters = ["Positive", "Negative", "Ten Commandments", "Passover", "Sukkot", "Rosh HaShanah", "Yom Kippur", "Speech", "Blasphemy", "Lashon HaRa", "Shavuot", "Business", "Intimate Relations", "Forbidden Relations", "Idolatry", "Avodah Zarah", "Kashrut", "Robbery", "Assault", "Children", "Courts", "Holidays", "Shabbat", "Levitical", "Holy Temple", "Conquest", "Applicable", "Not Applicable", "Applicable Only In Israel"]
    
}
